apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: gitops
spec:
  project: default
  source:
    repoURL: '"insert_repo"'
    path: infra/src/helm-charts/airbyte
    targetRevision: dev_repo
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: "orion-development"
    namespace: loader
    server: ""
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
